jobs:
  - name: dv-man
    type: manifest
    steps:
      - GET: dv-image
      - GET: dv-opts
      - GET: dv-params

  - name: dv-test
    type: ecsDeploy
    steps:
      - GET: dv-man
      - GET: env-test-aws

  - name: box-man
    type: manifest
    steps:
      - GET: box-image
      - GET: box-opts

  - name: box-t-beta
    type: ecsDeploy
    steps:
      - GET: box-man
      - GET: box-t-params
      - GET: env-test-aws
