jobs:
# manifest generation job for visualizer
  - name: dv-man
    type: manifest
    steps:
      - GET: dv-img
      - GET: dv-img-opts

# deployment job for visualizer
  - name: dv-test
    type: ecsDeploy
    steps:
      - GET: dv-man
      - GET: dv-params
      - GET: env-test-aws

# manifest generation job for BOX
  - name: box-man
    type: manifest
    steps:
      - GET: box-img
      - GET: box-img-opts

# TEST deployment job for BOX
  - name: box-test-aws
    type: ecsDeploy
    steps:
      - GET: box-man
      - GET: box-t-params
      - GET: env-test-aws
