jobs:
  - name: nginx-man
    type: manifest
    steps:
      - GET: nginx-image

  - name: nginx-ecs-deploy3
    type: ecsDeploy
    steps:
      - GET: nginx-man
      - GET: demoCluster

  - name: dv-man
    type: manifest
    steps:
      - GET: dv-image
      - GET: dv-opts
      - GET: dv-params

  - name: dv-test
    type: ecsDeploy
    steps:
      - GET: dv-man
      - GET: env-test

  - name: box-man
    type: manifest
    steps:
      - GET: box-image
      - GET: box-opts
      - GET: box-params

  - name: box-test
    type: ecsDeploy
    steps:
      - GET: box-man
      - GET: env-test
      - GET: box-scaler
