jobs:
  - name: dv-man
    type: manifest
    steps:
      - GET: dv-image
      - GET: dv-opts
      - GET: dv-params

  - name: dv-test
    type: ecsDeploy
    steps:
      - GET: dv-man
      - GET: env-test
      - GET: dv-scaler
