jobs:
  - name: nginx-man
    type: manifest
    steps:
      - GET: nginx-image

  - name: nginx-ecs-deploy3
    type: ecsDeploy
    steps:
      - GET: nginx-man
      - GET: demoCluster

  - name: dv-man
    type: manifest
    steps:
      - GET: dv-image
      - GET: dv-opts
      - GET: dv-image

  - name: dv-test
    type: ecsDeploy
    steps:
      - GET: dv-man
      - GET: env-test
